name: evangeisler
favicon: null
layout_spectrum: 0
typography_spectrum: 0.08936559
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#daa8b4'
    - '#c7e9ea'
    - '#0f1d0c'
    - '#71382d'
    - '#71695e'
  brandStrength: 0.6271288
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
