layout_spectrum: 0
color:
  saturation: 1
  brandStrength: 0.6271288
  lightness: 0
  brandColors:
    - '#CEF1FF'
    - '#0C0C0F'
    - '#2E4D77'
    - '#30B4FF'
    - '#FFF443'
  rhythmicContrast: 0
typography_spectrum: 0.08936559
name: evangeisler
